channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - pytorch~=2.0.1
  - pytorch-cuda~=11.8.0
  - mkl==2024.0.0
  - lightning~=2.0.7
  - torchmetrics~=1.0.3
  - transformers~=4.33
  - tensorboard
  - numba
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pydantic<2
  - pyarrow
  - ipykernel
  - zarr
  - fsspec
  - s3fs
  - boto3
  - mmseqs2
  - hhsuite
  - biopython
  - pyzstd
  - pip
