name: prosst
channels:
  - schrodinger
  - biocore
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.6.68=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.6=3
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - hmmer=3.1b2=0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.11.1.6=0
  - libcurand=10.3.7.68=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - pytorch=2.4.1=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - setuptools=69.5.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tmalign=20170708=h0e1e685_2
  - torchaudio=2.4.1=py310_cu121
  - torchtriton=3.0.0=py310
  - torchvision=0.19.1=py310_cu121
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.2=py310h06a4308_0
  - wheel=0.43.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.34.2
      - aenum==3.1.15
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.6
      - aiosignal==1.3.1
      - anyio==4.6.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - billiard==4.2.1
      - bio==1.7.1
      - biopython==1.84
      - biothings-client==0.3.1
      - biotite==0.41.2
      - biotraj==1.2.1
      - bleach==6.1.0
      - bokeh==3.6.0
      - cffi==1.17.1
      - click==8.1.7
      - cloudpathlib==0.19.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - datasets==3.0.1
      - debugpy==1.8.6
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.9
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - esm==3.0.4
      - evcouplings==0.2.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - fonttools==4.54.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gprofiler-official==1.0.0
      - gremlinpython==3.7.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.25.1
      - ipykernel==6.29.5
      - ipython==8.27.0
      - isodate==0.7.2
      - isoduration==20.11.0
      - jedi==0.19.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.7
      - llvmlite==0.43.0
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - msgpack==1.1.0
      - msgpack-numpy==0.4.8
      - multidict==6.1.0
      - multiprocess==0.70.17
      - mygene==3.2.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathos==0.3.3
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - pox==0.3.5
      - ppft==1.7.6.9
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - protobuf==5.28.2
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pycparser==2.22
      - pyg-lib==0.4.0+pt24cu121
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.9.11
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - ruamel-yaml==0.17.40
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.3.0
      - tokenizers==0.20.0
      - tomli==2.0.1
      - torch-cluster==1.6.3+pt24cu121
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt24cu121
      - torch-sparse==0.6.18+pt24cu121
      - torch-spline-conv==1.2.2+pt24cu121
      - torchmetrics==1.4.2
      - torchtext==0.18.0
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.45.0
      - types-python-dateutil==2.9.0.20240906
      - tzdata==2024.2
      - uri-template==1.3.0
      - wandb==0.18.1
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - xxhash==3.5.0
      - xyzservices==2024.9.0
      - yarl==1.12.1
