name: s3f
channels:
  - milagraph
  - pytorch-lts
  - pyg
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.6.4=hb9d3cd8_0
  - liblzma-devel=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - pip=24.3.1=pyh8b19718_0
  - python=3.8.20=h4a871b0_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.6.4=hbcc6ac9_0
  - xz-gpl-tools=5.6.4=hbcc6ac9_0
  - xz-tools=5.6.4=hb9d3cd8_0
  - pip:
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - async-timeout==5.0.1
    - attrs==25.1.0
    - biopython==1.83
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - contourpy==1.1.1
    - cycler==0.12.1
    - decorator==5.2.1
    - easydict==1.13
    - fair-esm==2.0.0
    - filelock==3.13.1
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2024.6.1
    - idna==3.10
    - importlib-resources==6.4.5
    - jinja2==3.1.4
    - joblib==1.4.2
    - keopscore==2.2.3
    - kiwisolver==1.4.7
    - lmdb==1.6.2
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mpmath==1.3.0
    - multidict==6.1.0
    - networkx==3.0
    - ninja==1.11.1.3
    - numpy==1.24.1
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.99
    - nvidia-nvtx-cu12==12.1.105
    - packaging==24.2
    - pandas==2.0.3
    - pillow==10.2.0
    - propcache==0.2.0
    - psutil==7.0.0
    - pybind11==2.13.6
    - pykeops==2.2.3
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - pytz==2025.1
    - pyyaml==6.0.2
    - rdkit-pypi==2022.9.5
    - requests==2.32.3
    - robust-laplacian==1.0.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - six==1.17.0
    - sympy==1.13.1
    - threadpoolctl==3.5.0
    - torch==2.4.0+cu121
    - torch-cluster==1.6.3+pt24cu124
    - torch-geometric==2.6.1
    - torch-scatter==2.1.2+pt24cu124
    - torchaudio==2.4.0+cu121
    - torchdrug==0.2.1
    - torchvision==0.19.0+cu121
    - tqdm==4.67.1
    - triton==3.0.0
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - urllib3==2.2.3
    - yarl==1.15.2
    - zipp==3.20.2